[package]
name = "mime_response"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime = "0.3.16"
reqwest = "0.11.3"
tokio = { version = "1.6.1", features = ["full"] }
error-chain = "0.12.4"